### ISSUE TITLE
Error on logon page

### ISSUE THREAD

**Issue by imagency** [zotonic/zotonic#1097]
Hello, I made a new installation of last zotonic master branch. Here I attached
 screenshot with errors on logon page.
![admin_logon_p _admin](https://cloud.githubusercontent.com/assets/11294532/11451319/9c33582c-95ca-11e5-917d-e86474b4d1cd.jpg)

**Comment by mworrell** [comment]
Try git pull - i think this has been fixed last night/morning.

Thanks for the report!

**Comment by imagency** [comment]
No, Marc, I already have the latest master version of zotonic, just tried git pull. So the bug is still there.

**Comment by mworrell** [comment]
@imagency I can't reproduce the issue with the newest master branch, can you check which version you have and if all is compiled?

**Comment by mworrell** [comment]
Can you let me know if the problem persists with the newest code? I really can't seem to reproduce it here.

**Comment by imagency** [comment]
Hello, Marc! Today I did:
git pull origin master
zotonic restart
The problem which I see now is not only on logon page, but on all admin interface pages. Look at screenshot.
![admin_edit_1](https://cloud.githubusercontent.com/assets/11294532/11526180/75aca66c-98e1-11e5-8509-da279cea2817.jpg)

**Comment by mworrell** [comment]
A couple of questions, to help with figuring this out:

 * Did you compile as well?
 * Are you using this on your local machine
 * Is the message repeating?
 * In the browser inspector/debugger, can you check the value of `z_comet` and `z_ws`?

**Comment by imagency** [comment]
1) Tried also to recompile my install of zotonic with
zotonic compile
but  with the same result.

2) No, my zotonic is installed on the vps ubuntu 14.04.1 server.
3) The message is repeating.
4) In browser console I have:
--------------------------------------
Don't know where to delegate incoming message  $.extend.misc.error @ z.adminwidget~z.live~z.notice~z.tooltip~z.dialog~z.feedback~z.formreplace~z.datepicker~z.menuedit~z…:2333z_transport_incoming_msg @ z.adminwidget~z.live~z.notice~z.tooltip~z.dialog~z.feedback~z.formreplace~z.datepicker~z.menuedit~z…:598z_transport_incoming @ z.adminwidget~z.live~z.notice~z.tooltip~z.dialog~z.feedback~z.formreplace~z.datepicker~z.menuedit~z…:567z_transport_handle_push_data @ z.adminwidget~z.live~z.notice~z.tooltip~z.dialog~z.feedback~z.formreplace~z.datepicker~z.menuedit~z…:1101$.ajax.statusCode.200 @ z.adminwidget~z.live~z.notice~z.tooltip~z.dialog~z.feedback~z.formreplace~z.datepicker~z.menuedit~z…:1060j @ jquery.ui.touch-punch.min~1507140032.js:2k.add @ jquery.ui.touch-punch.min~1507140032.js:2d.always @ jquery.ui.touch-punch.min~1507140032.js:2v.statusCode @ jquery.ui.touch-punch.min~1507140032.js:4x @ jquery.ui.touch-punch.min~1507140032.js:4b @ jquery.ui.touch-punch.min~1507140032.js:4
------------------------------------------------------------

z_ws:
--------
binaryType: "blob"
bufferedAmount: 0
extensions: ""
onclose: z_websocket_restart()
onerror: z_websocket_restart()
onmessage: (evt)
onopen: z_websocket_ping()
protocol: ""
readyState: 1
url: "ws://mytest-site.ru/websocket"
__proto__: WebSocket
--------------------------------------------

z_comet:
-------------
undefined

**Comment by mworrell** [comment]
Interesting, so it is coming via the web socket.
Is your site on your local machine?

@mmzeeman do you have any ideas?

**Comment by mmzeeman** [comment]
What is in the message?

**Comment by imagency** [comment]
Marc, can we contact via skype? My: im-design-

**Comment by mmzeeman** [comment]
@marc The error could have been there before, but only silently logging to console. I changed this recently.

@imagency The message itself should also be visible in the console log. Can you otherwise set a breakpoint to retrieve it.

**Comment by mworrell** [comment]
@mmzeeman I saw that change, and also updated some comet code that was pushing a `<<>>` message.  The weirdest thing is that I can't reproduce it.

@imagency my Skype handle is mworrell - will ping you there tomorrow.

**Comment by mworrell** [comment]
We have now a stacktrace in the browser of @imagency 

![screen shot 2015-12-03 at 21 38 47](https://cloud.githubusercontent.com/assets/38268/11573470/d03b4c5c-9a06-11e5-8be2-630689f076fd.png)

So, it is coming from an "empty" comet result. Looks like it is happening when we switch from comet to ws

**Comment by mworrell** [comment]
@mmzeeman I really can't find transporting an empty binary `<<>>` via comet in the code. Can you have a look and test as well?

Worst case we can catch the empty message in zotonic-1.0.js ...

**Comment by mmzeeman** [comment]
Yes, I will take a look at it. We are sending 0~~$ from somewhere... :-)

**Comment by mmzeeman** [comment]
@marc We should probably stop encoding <<>> and [] with z_transport:encode on the server. The comet controller currently sends "#$" when there is no data. It used to respond with a 204 when there was no data. This slowed down the comet reconnect slightly.

**Comment by mmzeeman** [comment]
@marc What do you think of this?

``` erlang
151 -spec data_encode(any()) -> {ok, binary()}.
152 data_encode([]) -> {ok, <<>>};
153 data_encode(<<>>) -> {ok, <<>>};
154 data_encode(Data) ->
155     z_ubf:encode(Data).
```

If you don't do this [] is encoded to #$ and <<>> to 0~~$

**Comment by mworrell** [comment]
That looks wrong....  `[]` should become `#$`

**Comment by mworrell** [comment]
But then ... empty is good as well.
And then catch empty in the zotonic.js?

**Comment by imagency** [comment]
Today I update my master branch with last commit of mmzeeman and error is gone.
Thank you!

**Comment by mworrell** [comment]
Good to hear that it is fixed!
